---
x-service-metadata: &service_metadata
  labels:
    fr.42.author: mmartin-
    fr.42.project: inception

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
      <<: *service_metadata
    command: "-g 'daemon off;'"
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
        uid: "33"
        gid: "33"
        mode: 0440
    container_name: nginx
    depends_on:
      db:
        condition: service_healthy
      wordpress:
        codndition: service_healthy
    deploy:
      endpoint_mode: dnsrr
      <<: *service_metadata
      mode: global
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 4s
    entrypoint: /usr/sbin/nginx
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "-f", "https://localhost"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
    hostname: nginx
    <<: *service_metadata
    networks:
      - front_tier
      - back_tier
    ports:
      - target: 443
        published: "${NGINX_PORT:?nginx external port is missing in .env}"
        host_ip: 127.0.0.1
        protocol: tcp
        mode: host
    secrets:
      - source: nginx_ssl_key
        target: nginx.key
        uid: "33"
        gid: "33"
        mode: 0440
      - source: nginx_ssl_crt
        target: nginx.crt
        uid: "33"
        gid: "33"
        mode: 0440
    volumes:
      - type: bind
        source: /Users/mariomartinmoreno/data/wordpress
        target: /var/www/mmartin.42.fr
        bind:
          create_host_path:
  wordpress:
    build:
      context: ./wordpress
      dockerfile: wordpress.Dockerfile
      <<: *service_metadata
    command: -F -c /etc/php/7.4/fpm/php.ini
    configs:
      - source: wordpress_php_config
        target: /etc/php/7.4/fpm/php.ini
        uid: "33"
        gid: "33"
        mode: 0440
      - source: wordpress_www_config
        target: /etc/php/7.4/fpm/pool.d/www.config
        uid: "33"
        gid: "33"
        mode: 0440
    container_name: wordpress
    depends_on:
      db:
        condition: service_healthy
    deploy:
      endpoint_mode: dnsrr
      <<: *service_metadata
      mode: global
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 4s
    entrypoint: "/usr/sbin/php-fpm7.4"
    expose:
      - "9000"
    healthcheck:
      test: ["CMD", "/bin/nc", "-zv", "localhost", "9000"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
    hostname: wordpress
    <<: *service_metadata
    networks:
      - back_tier
    volumes:
      - type: bind
        source: /Users/mariomartinmoreno/data/wordpress
        target: /var/www/
        read_only:
        bind:
          create_host_path:
  db:
    build:
      context: ./db
      dockerfile: db.Dockerfile
      # Args is used instead of direct ENV on Dockerfile to avoid empty configs
      args:
        DB_ROOT_PASS: "${DB_ROOT_PASS:?db root pass missing .env}"
        DB_WORDPRESS_USER: "${DB_WORDPRESS_USER:?db wp user undefined in .env}"
        DB_WORDPRESS_PASS: "${DB_WORDPRESS_PASS:?db wp pass undefined in .env}"
        DB_WORDPRESS_NAME: "${DB_WORDPRESS_NAME:?db wp db name undefined in .env}"
      <<: *service_metadata
    command: |
      --basedir=/usr
      --datadir=/var/lib/mysql
      --plugin-dir=/usr/lib/aarch64-linux-gnu/mariadb19/plugin
      --user=mysql
      --skip-log-error
      --pid-file=/run/mysqld/mysqld.pid
      --socket=/var/run/mysqld/mysqld.sock
      --bind-address=0.0.0.0
    container_name: db
    deploy:
      endpoint_mode: dnsrr
      <<: *service_metadata
      mode: global
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 4s
    entrypoint: /usr/bin/mysqld_safe
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "/usr/bin/mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
    hostname: db
    <<: *service_metadata
    networks:
      - back_tier
    volumes:
      - type: bind
        source: /Users/mariomartinmoreno/data/db
        target: /var/lib/mysql
        bind:
          create_host_path:

networks:
  front_tier:
  back_tier:

volumes:
  /Users/mariomartinmoreno/data/db:
  /Users/mariomartinmoreno/data/wordpress:

configs:
  nginx_config:
    file: ./nginx/nginx.conf
  wordpress_php_config:
    file: ./wordpress/php.ini
  wordpress_www_config:
    file: ./wordpress/www.conf

secrets:
  nginx_ssl_key:
    file: "./secrets/${NGINX_SSL_KEY:?nginx key undefined in .env}"
  nginx_ssl_crt:
    file: "./secrets/${NGINX_SSL_CRT:?nginx crt undefined in .env}"
